namespace D2RReimaginedTools.Models;

public record GameObject
{
    public int? Class { get; init; }
    public string? Name { get; init; }
    public string? Description { get; init; }
    public int? ID { get; init; }
    public string? Token { get; init; }
    public int? Selectable0 { get; init; }
    public int? Selectable1 { get; init; }
    public int? Selectable2 { get; init; }
    public int? Selectable3 { get; init; }
    public int? Selectable4 { get; init; }
    public int? Selectable5 { get; init; }
    public int? Selectable6 { get; init; }
    public int? Selectable7 { get; init; }
    public int? SizeX { get; init; }
    public int? SizeY { get; init; }
    public int? FrameCnt0 { get; init; }
    public int? FrameCnt1 { get; init; }
    public int? FrameCnt2 { get; init; }
    public int? FrameCnt3 { get; init; }
    public int? FrameCnt4 { get; init; }
    public int? FrameCnt5 { get; init; }
    public int? FrameCnt6 { get; init; }
    public int? FrameCnt7 { get; init; }
    public int? FrameDelta0 { get; init; }
    public int? FrameDelta1 { get; init; }
    public int? FrameDelta2 { get; init; }
    public int? FrameDelta3 { get; init; }
    public int? FrameDelta4 { get; init; }
    public int? FrameDelta5 { get; init; }
    public int? FrameDelta6 { get; init; }
    public int? FrameDelta7 { get; init; }
    public int? CycleAnim0 { get; init; }
    public int? CycleAnim1 { get; init; }
    public int? CycleAnim2 { get; init; }
    public int? CycleAnim3 { get; init; }
    public int? CycleAnim4 { get; init; }
    public int? CycleAnim5 { get; init; }
    public int? CycleAnim6 { get; init; }
    public int? CycleAnim7 { get; init; }
    public int? Lit0 { get; init; }
    public int? Lit1 { get; init; }
    public int? Lit2 { get; init; }
    public int? Lit3 { get; init; }
    public int? Lit4 { get; init; }
    public int? Lit5 { get; init; }
    public int? Lit6 { get; init; }
    public int? Lit7 { get; init; }
    public int? BlocksLight0 { get; init; }
    public int? BlocksLight1 { get; init; }
    public int? BlocksLight2 { get; init; }
    public int? BlocksLight3 { get; init; }
    public int? BlocksLight4 { get; init; }
    public int? BlocksLight5 { get; init; }
    public int? BlocksLight6 { get; init; }
    public int? BlocksLight7 { get; init; }
    public int? HasCollision0 { get; init; }
    public int? HasCollision1 { get; init; }
    public int? HasCollision2 { get; init; }
    public int? HasCollision3 { get; init; }
    public int? HasCollision4 { get; init; }
    public int? HasCollision5 { get; init; }
    public int? HasCollision6 { get; init; }
    public int? HasCollision7 { get; init; }
    public int? IsAttackable0 { get; init; }
    public int? Start0 { get; init; }
    public int? Start1 { get; init; }
    public int? Start2 { get; init; }
    public int? Start3 { get; init; }
    public int? Start4 { get; init; }
    public int? Start5 { get; init; }
    public int? Start6 { get; init; }
    public int? Start7 { get; init; }
    public int? EnvEffect { get; init; }
    public int? IsDoor { get; init; }
    public int? BlocksVis { get; init; }
    public int? Orientation { get; init; }
    public int? OrderFlag0 { get; init; }
    public int? OrderFlag1 { get; init; }
    public int? OrderFlag2 { get; init; }
    public int? OrderFlag3 { get; init; }
    public int? OrderFlag4 { get; init; }
    public int? OrderFlag5 { get; init; }
    public int? OrderFlag6 { get; init; }
    public int? OrderFlag7 { get; init; }
    public int? PreOperate { get; init; }
    public int? Mode0 { get; init; }
    public int? Mode1 { get; init; }
    public int? Mode2 { get; init; }
    public int? Mode3 { get; init; }
    public int? Mode4 { get; init; }
    public int? Mode5 { get; init; }
    public int? Mode6 { get; init; }
    public int? Mode7 { get; init; }
    public int? Yoffset { get; init; }
    public int? Xoffset { get; init; }
    public int? Draw { get; init; }
    public int? Red { get; init; }
    public int? Green { get; init; }
    public int? Blue { get; init; }
    public int? HD { get; init; }
    public int? TR { get; init; }
    public int? LG { get; init; }
    public int? RA { get; init; }
    public int? LA { get; init; }
    public int? RH { get; init; }
    public int? LH { get; init; }
    public int? SH { get; init; }
    public int? S1 { get; init; }
    public int? S2 { get; init; }
    public int? S3 { get; init; }
    public int? S4 { get; init; }
    public int? S5 { get; init; }
    public int? S6 { get; init; }
    public int? S7 { get; init; }
    public int? S8 { get; init; }
    public int? TotalPieces { get; init; }
    public int? SubClass { get; init; }
    public int? Xspace { get; init; }
    public int? Yspace { get; init; }
    public int? NameOffset { get; init; }
    public int? MonsterOK { get; init; }
    public int? ShrineFunction { get; init; }
    public int? Restore { get; init; }
    public int? Parm0 { get; init; }
    public int? Parm1 { get; init; }
    public int? Parm2 { get; init; }
    public int? Parm3 { get; init; }
    public int? Parm4 { get; init; }
    public int? Lockable { get; init; }
    public int? Gore { get; init; }
    public int? Sync { get; init; }
    public int? Damage { get; init; }
    public int? Overlay { get; init; }
    public int? CollisionSubst { get; init; }
    public int? Left { get; init; }
    public int? Top { get; init; }
    public int? Width { get; init; }
    public int? Height { get; init; }
    public int? OperateFn { get; init; }
    public int? PopulateFn { get; init; }
    public int? InitFn { get; init; }
    public int? ClientFn { get; init; }
    public int? RestoreVirgins { get; init; }
    public int? BlockMissile { get; init; }
    public int? DrawUnder { get; init; }
    public int? OpenWarp { get; init; }
    public int? AutoMap { get; init; }
}
