namespace D2RReimaginedTools.Models;

public record Missiles
{
    public string? MissileName { get; init; }
    public int MissileId { get; init; }
    public int? ClientDoFunction { get; init; }
    public int? ClientHitFunction { get; init; }
    public int? ServerDoFunction { get; init; }
    public int? ServerHitFunction { get; init; }
    public int? ServerDamageFunction { get; init; }
    public string? ServerCalculation1 { get; init; }
    public string? ServerCalculation1Description { get; init; }
    public int? Param1 { get; init; }
    public string? Param1Description { get; init; }
    public int? Param2 { get; init; }
    public string? Param2Description { get; init; }
    public int? Param3 { get; init; }
    public string? Param3Description { get; init; }
    public int? Param4 { get; init; }
    public string? Param4Description { get; init; }
    public int? Param5 { get; init; }
    public string? Param5Description { get; init; }
    public string? ClientCalculation1 { get; init; }
    public string? ClientCalculation1Description { get; init; }
    public int? ClientParam1 { get; init; }
    public string? ClientParam1Description { get; init; }
    public int? ClientParam2 { get; init; }
    public string? ClientParam2Description { get; init; }
    public int? ClientParam3 { get; init; }
    public string? ClientParam3Description { get; init; }
    public int? ClientParam4 { get; init; }
    public string? ClientParam4Description { get; init; }
    public int? ClientParam5 { get; init; }
    public string? ClientParam5Description { get; init; }
    public string? ServerHitCalculation1 { get; init; }
    public string? ServerHitCalculation1Description { get; init; }
    public int? ServerHitParam1 { get; init; }
    public string? ServerHitParam1Description { get; init; }
    public int? ServerHitParam2 { get; init; }
    public string? ServerHitParam2Description { get; init; }
    public int? ServerHitParam3 { get; init; }
    public string? ServerHitParam3Description { get; init; }
    public string? ClientHitCalculation1 { get; init; }
    public string? ClientHitCalculation1Description { get; init; }
    public int? ClientHitParam1 { get; init; }
    public string? ClientHitParam1Description { get; init; }
    public int? ClientHitParam2 { get; init; }
    public string? ClientHitParam2Description { get; init; }
    public int? ClientHitParam3 { get; init; }
    public string? ClientHitParam3Description { get; init; }
    public string? DamageCalculation1 { get; init; }
    public string? DamageCalculation1Description { get; init; }
    public string? DamageParam1 { get; init; }
    public string? DamageParam1Description { get; init; }
    public string? DamageParam2 { get; init; }
    public string? DamageParam2Description { get; init; }
    public int? Velocity { get; init; }
    public int? MaxVelocity { get; init; }
    public int? VelocityLevel { get; init; }
    public int? Acceleration { get; init; }
    public int? Range { get; init; }
    public int? LevelRange { get; init; }
    public int? Light { get; init; }
    public int? Flicker { get; init; }
    public int? Red { get; init; }
    public int? Green { get; init; }
    public int? Blue { get; init; }
    public int? InitSteps { get; init; }
    public int? Activate { get; init; }
    public int? LoopAnimation { get; init; }
    public string? CelFile { get; init; }
    public int? AnimationRate { get; init; }
    public int? AnimationLength { get; init; }
    public int? AnimationSpeed { get; init; }
    public int? RandomStart { get; init; }
    public int? SubLoop { get; init; }
    public int? SubStart { get; init; }
    public int? SubStop { get; init; }
    public int? CollideType { get; init; }
    public int? CollideKill { get; init; }
    public int? CollideFriend { get; init; }
    public int? LastCollide { get; init; }
    public int? Collision { get; init; }
    public int? ClientCollision { get; init; }
    public int? ClientSend { get; init; }
    public int? NextHit { get; init; }
    public int? NextDelay { get; init; }
    public int? XOffset { get; init; }
    public int? YOffset { get; init; }
    public int? ZOffset { get; init; }
    public int? Size { get; init; }
    public int? SourceTown { get; init; }
    public int? ClientSourceTown { get; init; }
    public int? CanDestroy { get; init; }
    public int? ToHit { get; init; }
    public int? AlwaysExplode { get; init; }
    public string? Explosion { get; init; }
    public int? Town { get; init; }
    public int? NoUniqueMod { get; init; }
    public int? NoMultiShot { get; init; }
    public int? Holy { get; init; }
    public int? CanSlow { get; init; }
    public int? ReturnFire { get; init; }
    public int? GetHit { get; init; }
    public int? SoftHit { get; init; }
    public int? KnockBack { get; init; }
    public string? Trans { get; init; }
    public int? Pierce { get; init; }
    public int? MissileSkill { get; init; }
    public string? Skill { get; init; }
    public int? ResultFlags { get; init; }
    public int? HitFlags { get; init; }
    public int? HitShift { get; init; }
    public int? ApplyMastery { get; init; }
    public int? SourceDamage { get; init; }
    public int? Half2HSource { get; init; }
    public int? SourceMissileDamage { get; init; }
    public int? MinDamage { get; init; }
    public int? MinLevelDamage1 { get; init; }
    public int? MinLevelDamage2 { get; init; }
    public int? MinLevelDamage3 { get; init; }
    public int? MinLevelDamage4 { get; init; }
    public int? MinLevelDamage5 { get; init; }
    public int? MaxDamage { get; init; }
    public int? MaxLevelDamage1 { get; init; }
    public int? MaxLevelDamage2 { get; init; }
    public int? MaxLevelDamage3 { get; init; }
    public int? MaxLevelDamage4 { get; init; }
    public int? MaxLevelDamage5 { get; init; }
    public string? DamageSymPerCalculation { get; init; }
    public string? ElementalType { get; init; }
    public int? ElementalMin { get; init; }
    public int? MinElementalLevel1 { get; init; }
    public int? MinElementalLevel2 { get; init; }
    public int? MinElementalLevel3 { get; init; }
    public int? MinElementalLevel4 { get; init; }
    public int? MinElementalLevel5 { get; init; }
    public int? ElementalMax { get; init; }
    public int? MaxElementalLevel1 { get; init; }
    public int? MaxElementalLevel2 { get; init; }
    public int? MaxElementalLevel3 { get; init; }
    public int? MaxElementalLevel4 { get; init; }
    public int? MaxElementalLevel5 { get; init; }
    public string? ElementalDamageSymPerCalculation { get; init; }
    public string? ElementalLength { get; init; }
    public int? ElementalLevelLength1 { get; init; }
    public int? ElementalLevelLength2 { get; init; }
    public int? ElementalLevelLength3 { get; init; }
    public string? HitClass { get; init; }
    public int? NumberOfDirections { get; init; }
    public int? LocalBlood { get; init; }
    public int? DamageRate { get; init; }
    public string? TravelSound { get; init; }
    public string? HitSound { get; init; }
    public string? ProgressSound { get; init; }
    public string? ProgressOverlay { get; init; }
    public string? ExplosionMissile { get; init; }
    public string? SubMissile1 { get; init; }
    public string? SubMissile2 { get; init; }
    public string? SubMissile3 { get; init; }
    public string? HitSubMissile1 { get; init; }
    public string? HitSubMissile2 { get; init; }
    public string? HitSubMissile3 { get; init; }
    public string? HitSubMissile4 { get; init; }
    public string? ClientSubMissile1 { get; init; }
    public string? ClientSubMissile2 { get; init; }
    public string? ClientSubMissile3 { get; init; }
    public string? ClientHitSubMissile1 { get; init; }
    public string? ClientHitSubMissile2 { get; init; }
    public string? ClientHitSubMissile3 { get; init; }
    public string? ClientHitSubMissile4 { get; init; }
}

