namespace D2RReimaginedTools.Models;

public record Missiles
{
    public string? MissileName { get; init; }
    public int? MissileId { get; init; }
    public int? ClientDoFunction { get; init; }
    public int? ClientHitFunction { get; init; }
    public int? ServerDoFunction { get; init; }
    public int? ServerHitFunction { get; init; }
    public int? ServerDamageFunction { get; init; }
    public string? ServerCalculation1 { get; init; }
    public string? ServerCalculation1Description { get; init; }
    public string? Parameter1 { get; init; }
    public string? Parameter1Description { get; init; }
    public string? Parameter2 { get; init; }
    public string? Parameter2Description { get; init; }
    public string? Parameter3 { get; init; }
    public string? Parameter3Description { get; init; }
    public string? Parameter4 { get; init; }
    public string? Parameter4Description { get; init; }
    public string? Parameter5 { get; init; }
    public string? Parameter5Description { get; init; }
    public string? ClientCalculation1 { get; init; }
    public string? ClientCalculation1Description { get; init; }
    public string? ClientParameter1 { get; init; }
    public string? ClientParameter1Description { get; init; }
    public string? ClientParameter2 { get; init; }
    public string? ClientParameter2Description { get; init; }
    public string? ClientParameter3 { get; init; }
    public string? ClientParameter3Description { get; init; }
    public string? ClientParameter4 { get; init; }
    public string? ClientParameter4Description { get; init; }
    public string? ClientParameter5 { get; init; }
    public string? ClientParameter5Description { get; init; }
    public string? ServerHitCalculation1 { get; init; }
    public string? ServerHitCalculation1Description { get; init; }
    public string? ServerHitParameter1 { get; init; }
    public string? ServerHitParameter1Description { get; init; }
    public string? ServerHitParameter2 { get; init; }
    public string? ServerHitParameter2Description { get; init; }
    public string? ServerHitParameter3 { get; init; }
    public string? ServerHitParameter3Description { get; init; }
    public string? ClientHitCalculation1 { get; init; }
    public string? ClientHitParameter1Description { get; init; }
    public string? ClientHitParameter2Description { get; init; }
    public string? ClientHitParameter3Description { get; init; }
    public string? DamageCalculation1 { get; init; }
    public string? DamageParameter1Description { get; init; }
    public string? DamageParameter2Description { get; init; }
    public int? Velocity { get; init; }
    public int? MaxVelocity { get; init; }
    public int? VelocityLevel { get; init; }
    public int? Acceleration { get; init; }
    public int? Range { get; init; }
    public int? LevelRange { get; init; }
    public int? Light { get; init; }
    public int? Flicker { get; init; }
    public int? Red { get; init; }
    public int? Green { get; init; }
    public int? Blue { get; init; }
    public int? InitialSteps { get; init; }
    public int? Activate { get; init; }
    public int? LoopAnimation { get; init; }
    public string? CelFile { get; init; }
    public int? AnimationRate { get; init; }
    public int? AnimationLength { get; init; }
    public int? AnimationSpeed { get; init; }
    public int? RandomStart { get; init; }
    public int? SubLoop { get; init; }
    public int? SubStart { get; init; }
    public int? SubStop { get; init; }
    public int? CollisionType { get; init; }
    public int? CollisionKill { get; init; }
    public int? CollisionFriend { get; init; }
    public int? LastCollision { get; init; }
    public int? Collision { get; init; }
    public int? ClientCollision { get; init; }
    public int? ClientSend { get; init; }
    public int? NextHit { get; init; }
    public int? NextDelay { get; init; }
    public int? XOffset { get; init; }
    public int? YOffset { get; init; }
    public int? ZOffset { get; init; }
    public int? Size { get; init; }
    public int? SourceTown { get; init; }
    public int? ClientSourceTown { get; init; }
    public int? CanDestroy { get; init; }
    public int? ToHit { get; init; }
    public int? AlwaysExplode { get; init; }
    public int? Explosion { get; init; }
    public int? Town { get; init; }
    public int? NoUniqueModifier { get; init; }
    public int? NoMultiShot { get; init; }
    public int? Holy { get; init; }
    public int? CanSlow { get; init; }
    public int? ReturnFire { get; init; }
    public int? GetHit { get; init; }
    public int? SoftHit { get; init; }
    public int? KnockBack { get; init; }
    public int? Transform { get; init; }
    public int? Pierce { get; init; }
    public int? MissileSkill { get; init; }
    public string? Skill { get; init; }
    public int? ResultFlags { get; init; }
    public int? HitFlags { get; init; }
    public int? HitShift { get; init; }
    public int? ApplyMastery { get; init; }
    public int? SourceDamage { get; init; }
    public int? HalfTwoHandedSource { get; init; }
    public int? SourceMissileDamage { get; init; }
    public int? MinimumDamage { get; init; }
    public int? MinimumLevelDamage1 { get; init; }
    public int? MinimumLevelDamage2 { get; init; }
    public int? MinimumLevelDamage3 { get; init; }
    public int? MinimumLevelDamage4 { get; init; }
    public int? MinimumLevelDamage5 { get; init; }
    public int? MaximumDamage { get; init; }
    public int? MaximumLevelDamage1 { get; init; }
    public int? MaximumLevelDamage2 { get; init; }
    public int? MaximumLevelDamage3 { get; init; }
    public int? MaximumLevelDamage4 { get; init; }
    public int? MaximumLevelDamage5 { get; init; }
    public int? DamageSymbolPerCalculation { get; init; }
    public string? ElementType { get; init; }
    public int? ElementMinimum { get; init; }
    public int? MinimumElementLevel1 { get; init; }
    public int? MinimumElementLevel2 { get; init; }
    public int? MinimumElementLevel3 { get; init; }
    public int? MinimumElementLevel4 { get; init; }
    public int? MinimumElementLevel5 { get; init; }
    public int? ElementMaximum { get; init; }
    public int? MaximumElementLevel1 { get; init; }
    public int? MaximumElementLevel2 { get; init; }
    public int? MaximumElementLevel3 { get; init; }
    public int? MaximumElementLevel4 { get; init; }
    public int? MaximumElementLevel5 { get; init; }
    public string? ElementDamageSymbolPerCalculation { get; init; }
    public int? ElementLength { get; init; }
    public int? ElementLevelLength1 { get; init; }
    public int? ElementLevelLength2 { get; init; }
    public int? ElementLevelLength3 { get; init; }
    public int? HitClass { get; init; }
    public int? NumberOfDirections { get; init; }
    public int? LocalBlood { get; init; }
    public int? DamageRate { get; init; }
    public string? TravelSound { get; init; }
    public string? HitSound { get; init; }
    public string? ProgressionSound { get; init; }
    public string? ProgressionOverlay { get; init; }
    public string? ExplosionMissile { get; init; }
    public string? SubMissile1 { get; init; }
    public string? SubMissile2 { get; init; }
    public string? SubMissile3 { get; init; }
    public string? HitSubMissile1 { get; init; }
    public string? HitSubMissile2 { get; init; }
    public string? HitSubMissile3 { get; init; }
    public string? HitSubMissile4 { get; init; }
    public string? ClientSubMissile1 { get; init; }
    public string? ClientSubMissile2 { get; init; }
    public string? ClientSubMissile3 { get; init; }
    public string? ClientHitSubMissile1 { get; init; }
    public string? ClientHitSubMissile2 { get; init; }
    public string? ClientHitSubMissile3 { get; init; }
    public string? ClientHitSubMissile4 { get; init; }
}

