namespace D2RReimaginedTools.Models;

public record MonStats2
{
    public string? Id { get; init; }
    public int? HcIdx { get; init; }
    public int? Height { get; init; }
    public int? OverlayHeight { get; init; }
    public int? PixHeight { get; init; }
    public int? SizeX { get; init; }
    public int? SizeY { get; init; }
    public int? SpawnCol { get; init; }
    public string? MeleeRng { get; init; }
    public string? BaseW { get; init; }
    public int? HitClass { get; init; }
    public string? HDv { get; init; }
    public string? TRv { get; init; }
    public string? LGv { get; init; }
    public string? Rav { get; init; }
    public string? Lav { get; init; }
    public string? RHv { get; init; }
    public string? LHv { get; init; }
    public string? SHv { get; init; }
    public string? S1v { get; init; }
    public string? S2v { get; init; }
    public string? S3v { get; init; }
    public string? S4v { get; init; }
    public string? S5v { get; init; }
    public string? S6v { get; init; }
    public string? S7v { get; init; }
    public string? S8v { get; init; }
    public string? HD { get; init; }
    public string? TR { get; init; }
    public string? LG { get; init; }
    public string? RA { get; init; }
    public string? LA { get; init; }
    public string? RH { get; init; }
    public string? LH { get; init; }
    public string? SH { get; init; }
    public string? S1 { get; init; }
    public string? S2 { get; init; }
    public string? S3 { get; init; }
    public string? S4 { get; init; }
    public string? S5 { get; init; }
    public string? S6 { get; init; }
    public string? S7 { get; init; }
    public string? S8 { get; init; }
    public int? TotalPieces { get; init; }
    public int? MDT { get; init; }
    public int? MNU { get; init; }
    public int? MWL { get; init; }
    public int? MGH { get; init; }
    public int? MA1 { get; init; }
    public int? MA2 { get; init; }
    public int? MBL { get; init; }
    public int? MSC { get; init; }
    public int? MS1 { get; init; }
    public int? MS2 { get; init; }
    public int? MS3 { get; init; }
    public int? MS4 { get; init; }
    public int? MDD { get; init; }
    public int? MKB { get; init; }
    public int? MSQ { get; init; }
    public int? MRN { get; init; }
    public int? DDT { get; init; }
    public int? DNU { get; init; }
    public int? DWL { get; init; }
    public int? DGH { get; init; }
    public int? DA1 { get; init; }
    public int? DA2 { get; init; }
    public int? DBL { get; init; }
    public int? DSC { get; init; }
    public int? DS1 { get; init; }
    public int? DS2 { get; init; }
    public int? DS3 { get; init; }
    public int? DS4 { get; init; }
    public int? DDD { get; init; }
    public int? DKB { get; init; }
    public int? DSQ { get; init; }
    public int? DRN { get; init; }
    public int? A1mv { get; init; }
    public int? A2mv { get; init; }
    public int? SCmv { get; init; }
    public int? S1mv { get; init; }
    public int? S2mv { get; init; }
    public int? S3mv { get; init; }
    public int? S4mv { get; init; }
    public int? NoGfxHitTest { get; init; }
    public int? HtTop { get; init; }
    public int? HtLeft { get; init; }
    public int? HtWidth { get; init; }
    public int? HtHeight { get; init; }
    public int? Restore { get; init; }
    public string? AutomapCel { get; init; }
    public int? NoMap { get; init; }
    public int? NoOvly { get; init; }
    public int? IsSel { get; init; }
    public int? AlSel { get; init; }
    public int? NoSel { get; init; }
    public int? ShiftSel { get; init; }
    public int? CorpseSel { get; init; }
    public int? IsAtt { get; init; }
    public int? Revive { get; init; }
    public int? LimitCorpses { get; init; }
    public int? Critter { get; init; }
    public int? Small { get; init; }
    public int? Large { get; init; }
    public int? Soft { get; init; }
    public int? Inert { get; init; }
    public int? ObjCol { get; init; }
    public int? DeadCol { get; init; }
    public int? UnflatDead { get; init; }
    public string? Shadow { get; init; }
    public int? NoUniqueShift { get; init; }
    public string? CompositeDeath { get; init; }
    public string? LocalBlood { get; init; }
    public bool? Bleed { get; init; }
    public string? Light { get; init; }
    public int? LightR { get; init; }
    public int? LightG { get; init; }
    public int? LightB { get; init; }
    public string? Utrans { get; init; }
    public string? UtransN { get; init; }
    public string? UtransH { get; init; }
    public int? InfernoLen { get; init; }
    public string? InfernoAnim { get; init; }
    public int? InfernoRollback { get; init; }
    public string? ResurrectMode { get; init; }
    public string? ResurrectSkill { get; init; }
    public string? SpawnUniqueMod { get; init; }
}