namespace D2RReimaginedTools.Models;

public record MonStat
{
    public string? Id { get; set; }
    public int HcIdx { get; set; }
    public string? BaseId { get; set; }
    public string? NextInClass { get; set; }
    public int TransLvl { get; set; }
    public string? NameStr { get; set; }
    public string? MonStatsEx { get; set; }
    public string? MonProp { get; set; }
    public string? MonType { get; set; }
    public string? AI { get; set; }
    public string? DescStr { get; set; }
    public string? Code { get; set; }
    public int Enabled { get; set; }
    public string? RangedType { get; set; }
    public string? PlaceSpawn { get; set; }
    public string? Spawn { get; set; }
    public string? SpawnX { get; set; }
    public string? SpawnY { get; set; }
    public string? SpawnMode { get; set; }
    public string? Minion1 { get; set; }
    public string? Minion2 { get; set; }
    public string? SetBoss { get; set; }
    public string? BossXfer { get; set; }
    public string? PartyMin { get; set; }
    public string? PartyMax { get; set; }
    public string? MinGrp { get; set; }
    public string? MaxGrp { get; set; }
    public string? SparsePopulate { get; set; }
    public int? Velocity { get; set; }
    public int? Run { get; set; }
    public string? Rarity { get; set; }
    public int? Level { get; set; }
    public int? LevelN { get; set; }
    public int? LevelH { get; set; }
    public string? MonSound { get; set; }
    public string? UMonSound { get; set; }
    public string? Threat { get; set; }
    public string? AIDel { get; set; }
    public string? AIDelN { get; set; }
    public string? AIDelH { get; set; }
    public string? AIDist { get; set; }
    public string? AIDistN { get; set; }
    public string? AIDistH { get; set; }
    public string? AIP1 { get; set; }
    public string? AIP1N { get; set; }
    public string? AIP1H { get; set; }
    public string? AIP2 { get; set; }
    public string? AIP2N { get; set; }
    public string? AIP2H { get; set; }
    public string? AIP3 { get; set; }
    public string? AIP3N { get; set; }
    public string? AIP3H { get; set; }
    public string? AIP4 { get; set; }
    public string? AIP4N { get; set; }
    public string? AIP4H { get; set; }
    public string? AIP5 { get; set; }
    public string? AIP5N { get; set; }
    public string? AIP5H { get; set; }
    public string? AIP6 { get; set; }
    public string? AIP6N { get; set; }
    public string? AIP6H { get; set; }
    public string? AIP7 { get; set; }
    public string? AIP7N { get; set; }
    public string? AIP7H { get; set; }
    public string? AIP8 { get; set; }
    public string? AIP8N { get; set; }
    public string? AIP8H { get; set; }
    public string? MissA1 { get; set; }
    public string? MissA2 { get; set; }
    public string? MissS1 { get; set; }
    public string? MissS2 { get; set; }
    public string? MissS3 { get; set; }
    public string? MissS4 { get; set; }
    public string? MissC { get; set; }
    public string? MissSQ { get; set; }
    public string? Align { get; set; }
    public string? IsSpawn { get; set; }
    public string? IsMelee { get; set; }
    public string? Npc { get; set; }
    public string? Interact { get; set; }
    public string? Inventory { get; set; }
    public string? InTown { get; set; }
    public string? LUndead { get; set; }
    public string? HUndead { get; set; }
    public string? Demon { get; set; }
    public string? Flying { get; set; }
    public string? OpenDoors { get; set; }
    public string? Boss { get; set; }
    public string? PrimeEvil { get; set; }
    public string? Killable { get; set; }
    public string? SwitchAI { get; set; }
    public string? NoAura { get; set; }
    public string? NoMultiShot { get; set; }
    public string? NeverCount { get; set; }
    public string? PetIgnore { get; set; }
    public string? DeathDmg { get; set; }
    public string? GenericSpawn { get; set; }
    public string? Zoo { get; set; }
    public string? CannotDesecrate { get; set; }
    public string? RightArmItemType { get; set; }
    public string? LeftArmItemType { get; set; }
    public string? CanNotUseTwoHandedItems { get; set; }
    public string? SendSkills { get; set; }
    public string? Skill1 { get; set; }
    public string? Sk1Mode { get; set; }
    public string? Sk1Lvl { get; set; }
    public string? Skill2 { get; set; }
    public string? Sk2Mode { get; set; }
    public string? Sk2Lvl { get; set; }
    public string? Eol { get; set; }
}
