namespace D2RReimaginedTools.Models;

public record MonStat
{
    public string? Id { get; set; }
    public int HcIdx { get; set; }
    public string? BaseId { get; set; }
    public string? NextInClass { get; set; }
    public int TransLvl { get; set; }
    public string? NameStr { get; set; }
    public string? MonStatsEx { get; set; }
    public string? MonProp { get; set; }
    public string? MonType { get; set; }
    public string? AI { get; set; }
    public string? DescStr { get; set; }
    public string? Code { get; set; }
    public int Enabled { get; set; }
    public string? RangedType { get; set; }
    public string? PlaceSpawn { get; set; }
    public string? Spawn { get; set; }
    public string? SpawnX { get; set; }
    public string? SpawnY { get; set; }
    public string? SpawnMode { get; set; }
    public string? Minion1 { get; set; }
    public string? Minion2 { get; set; }
    public string? SetBoss { get; set; }
    public string? BossXfer { get; set; }
    public string? PartyMin { get; set; }
    public string? PartyMax { get; set; }
    public string? MinGrp { get; set; }
    public string? MaxGrp { get; set; }
    public string? SparsePopulate { get; set; }
    public int? Velocity { get; set; }
    public int? Run { get; set; }
    public string? Rarity { get; set; }
    public int? Level { get; set; }
    public int? LevelN { get; set; }
    public int? LevelH { get; set; }
    public string? MonSound { get; set; }
    public string? UMonSound { get; set; }
    public string? Threat { get; set; }
    public string? AIDel { get; set; }
    public string? AIDelN { get; set; }
    public string? AIDelH { get; set; }
    public string? AIDist { get; set; }
    public string? AIDistN { get; set; }
    public string? AIDistH { get; set; }
    public string? AIP1 { get; set; }
    public string? AIP1N { get; set; }
    public string? AIP1H { get; set; }
    public string? AIP2 { get; set; }
    public string? AIP2N { get; set; }
    public string? AIP2H { get; set; }
    public string? AIP3 { get; set; }
    public string? AIP3N { get; set; }
    public string? AIP3H { get; set; }
    public string? AIP4 { get; set; }
    public string? AIP4N { get; set; }
    public string? AIP4H { get; set; }
    public string? AIP5 { get; set; }
    public string? AIP5N { get; set; }
    public string? AIP5H { get; set; }
    public string? AIP6 { get; set; }
    public string? AIP6N { get; set; }
    public string? AIP6H { get; set; }
    public string? AIP7 { get; set; }
    public string? AIP7N { get; set; }
    public string? AIP7H { get; set; }
    public string? AIP8 { get; set; }
    public string? AIP8N { get; set; }
    public string? AIP8H { get; set; }
    public string? MissA1 { get; set; }
    public string? MissA2 { get; set; }
    public string? MissS1 { get; set; }
    public string? MissS2 { get; set; }
    public string? MissS3 { get; set; }
    public string? MissS4 { get; set; }
    public string? MissC { get; set; }
    public string? MissSQ { get; set; }
    public string? Align { get; set; }
    public string? IsSpawn { get; set; }
    public string? IsMelee { get; set; }
    public string? Npc { get; set; }
    public string? Interact { get; set; }
    public string? Inventory { get; set; }
    public string? InTown { get; set; }
    public string? LUndead { get; set; }
    public string? HUndead { get; set; }
    public string? Demon { get; set; }
    public string? Flying { get; set; }
    public string? OpenDoors { get; set; }
    public string? Boss { get; set; }
    public string? PrimeEvil { get; set; }
    public string? Killable { get; set; }
    public string? SwitchAI { get; set; }
    public string? NoAura { get; set; }
    public string? NoMultiShot { get; set; }
    public string? NeverCount { get; set; }
    public string? PetIgnore { get; set; }
    public string? DeathDmg { get; set; }
    public string? GenericSpawn { get; set; }
    public string? Zoo { get; set; }
    public string? CannotDesecrate { get; set; }
    public string? RightArmItemType { get; set; }
    public string? LeftArmItemType { get; set; }
    public string? CanNotUseTwoHandedItems { get; set; }
    public string? SendSkills { get; set; }
    public string Skill1 { get; set; }
    public string Sk1Mode { get; set; }
    public int? Sk1Lvl { get; set; }
    public string Skill2 { get; set; }
    public string Sk2Mode { get; set; }
    public int? Sk2Lvl { get; set; }
    public string Skill3 { get; set; }
    public string Sk3Mode { get; set; }
    public int? Sk3Lvl { get; set; }
    public string Skill4 { get; set; }
    public string Sk4Mode { get; set; }
    public int? Sk4Lvl { get; set; }
    public string Skill5 { get; set; }
    public string Sk5Mode { get; set; }
    public int? Sk5Lvl { get; set; }
    public string Skill6 { get; set; }
    public string Sk6Mode { get; set; }
    public int? Sk6Lvl { get; set; }
    public string Skill7 { get; set; }
    public string Sk7Mode { get; set; }
    public int? Sk7Lvl { get; set; }
    public string Skill8 { get; set; }
    public string Sk8Mode { get; set; }
    public int? Sk8Lvl { get; set; }
    public int? Drain { get; set; }
    public int? DrainN { get; set; }
    public int? DrainH { get; set; }
    public int? ColdEffect { get; set; }
    public int? ColdEffectN { get; set; }
    public int? ColdEffectH { get; set; }
    public int? ResDm { get; set; }
    public int? ResMa { get; set; }
    public int? ResFi { get; set; }
    public int? ResLi { get; set; }
    public int? ResCo { get; set; }
    public int? ResPo { get; set; }
    public int? ResDmN { get; set; }
    public int? ResMaN { get; set; }
    public int? ResFiN { get; set; }
    public int? ResLiN { get; set; }
    public int? ResCoN { get; set; }
    public int? ResPoN { get; set; }
    public int? ResDmH { get; set; }
    public int? ResMaH { get; set; }
    public int? ResFiH { get; set; }
    public int? ResLiH { get; set; }
    public int? ResCoH { get; set; }
    public int? ResPoH { get; set; }
    public int? DamageRegen { get; set; }
    public int? SkillDamage { get; set; }
    public int? NoRatio { get; set; }
    public int? ShieldBlockOverride { get; set; }
    public int? ToBlock { get; set; }
    public int? ToBlockN { get; set; }
    public int? ToBlockH { get; set; }
    public int? Crit { get; set; }
    public int? MinHP { get; set; }
    public int? MaxHP { get; set; }
    public int? AC { get; set; }
    public int? Exp { get; set; }
    public int? A1MinD { get; set; }
    public int? A1MaxD { get; set; }
    public int? A1TH { get; set; }
    public int? A2MinD { get; set; }
    public int? A2MaxD { get; set; }
    public int? A2TH { get; set; }
    public int? S1MinD { get; set; }
    public int? S1MaxD { get; set; }
    public int? S1TH { get; set; }
    public int? MinHPN { get; set; }
    public int? MaxHPN { get; set; }
    public int? ACN { get; set; }
    public int? ExpN { get; set; }
    public int? A1MinDN { get; set; }
    public int? A1MaxDN { get; set; }
    public int? A1THN { get; set; }
    public int? A2MinDN { get; set; }
    public int? A2MaxDN { get; set; }
    public int? A2THN { get; set; }
    public int? S1MinDN { get; set; }
    public int? S1MaxDN { get; set; }
    public int? S1THN { get; set; }
    public int? MinHPH { get; set; }
    public int? MaxHPH { get; set; }
    public int? ACH { get; set; }
    public int? ExpH { get; set; }
    public int? A1MinDH { get; set; }
    public int? A1MaxDH { get; set; }
    public int? A1THH { get; set; }
    public int? A2MinDH { get; set; }
    public int? A2MaxDH { get; set; }
    public int? A2THH { get; set; }
    public int? S1MinDH { get; set; }
    public int? S1MaxDH { get; set; }
    public int? S1THH { get; set; }
     public string El1Mode { get; set; }
    public string El1Type { get; set; }
    public int? El1Pct { get; set; }
    public int? El1MinD { get; set; }
    public int? El1MaxD { get; set; }
    public int? El1Dur { get; set; }
    public int? El1PctN { get; set; }
    public int? El1MinDN { get; set; }
    public int? El1MaxDN { get; set; }
    public int? El1DurN { get; set; }
    public int? El1PctH { get; set; }
    public int? El1MinDH { get; set; }
    public int? El1MaxDH { get; set; }
    public int? El1DurH { get; set; }

    public string El2Mode { get; set; }
    public string El2Type { get; set; }
    public int? El2Pct { get; set; }
    public int? El2MinD { get; set; }
    public int? El2MaxD { get; set; }
    public int? El2Dur { get; set; }
    public int? El2PctN { get; set; }
    public int? El2MinDN { get; set; }
    public int? El2MaxDN { get; set; }
    public int? El2DurN { get; set; }
    public int? El2PctH { get; set; }
    public int? El2MinDH { get; set; }
    public int? El2MaxDH { get; set; }
    public int? El2DurH { get; set; }

    public string El3Mode { get; set; }
    public string El3Type { get; set; }
    public int? El3Pct { get; set; }
    public int? El3MinD { get; set; }
    public int? El3MaxD { get; set; }
    public int? El3Dur { get; set; }
    public int? El3PctN { get; set; }
    public int? El3MinDN { get; set; }
    public int? El3MaxDN { get; set; }
    public int? El3DurN { get; set; }
    public int? El3PctH { get; set; }
    public int? El3MinDH { get; set; }
    public int? El3MaxDH { get; set; }
    public int? El3DurH { get; set; }
    public string? TreasureClass { get; set; }
    public string? TreasureClassChamp { get; set; }
    public string? TreasureClassUnique { get; set; }
    public string? TreasureClassQuest { get; set; }
    public string? TreasureClassDesecrated { get; set; }
    public string? TreasureClassDesecratedChamp { get; set; }
    public string? TreasureClassDesecratedUnique { get; set; }
    public string? TreasureClassN { get; set; }
    public string? TreasureClassChampN { get; set; }
    public string? TreasureClassUniqueN { get; set; }
    public string? TreasureClassQuestN { get; set; }
    public string? TreasureClassDesecratedN { get; set; }
    public string? TreasureClassDesecratedChampN { get; set; }
    public string? TreasureClassDesecratedUniqueN { get; set; }
    public string? TreasureClassH { get; set; }
    public string? TreasureClassChampH { get; set; }
    public string? TreasureClassUniqueH { get; set; }
    public string? TreasureClassQuestH { get; set; }
    public string? TreasureClassDesecratedH { get; set; }
    public string? TreasureClassDesecratedChampH { get; set; }
    public string? TreasureClassDesecratedUniqueH { get; set; }
    public int? TCQuestId { get; set; }
    public int? TCQuestCP { get; set; }
    public int? SplEndDeath { get; set; }
    public int? SplGetModeChart { get; set; }
    public int? SplEndGeneric { get; set; }
    public int? SplClientEnd { get; set; }
    public int? Eol { get; set; }
}
