namespace D2RReimaginedTools.Models;

public record MonStat
{
    public string? Id { get; set; }
    public int HcIdx { get; set; }
    public string? BaseId { get; set; }
    public string? NextInClass { get; set; }
    public int TransLvl { get; set; }
    public string? NameStr { get; set; }
    public string? MonStatsEx { get; set; }
    public string? MonProp { get; set; }
    public string? MonType { get; set; }
    public string? AI { get; set; }
    public string? DescStr { get; set; }
    public string? Code { get; set; }
    public bool? Enabled { get; set; }
    public bool? RangedType { get; set; }
    public bool? PlaceSpawn { get; set; }
    public string? Spawn { get; set; }
    public int? SpawnX { get; set; }
    public int? SpawnY { get; set; }
    public string? SpawnMode { get; set; }
    public string? Minion1 { get; set; }
    public string? Minion2 { get; set; }
    public bool? SetBoss { get; set; }
    public bool? BossXfer { get; set; }
    public int? PartyMin { get; set; }
    public int? PartyMax { get; set; }
    public int? MinGrp { get; set; }
    public int? MaxGrp { get; set; }
    public int? SparsePopulate { get; set; }
    public int? Velocity { get; set; }
    public int? Run { get; set; }
    public int? Rarity { get; set; }
    public int? Level { get; set; }
    public int? LevelN { get; set; }
    public int? LevelH { get; set; }
    public string? MonSound { get; set; }
    public string? UMonSound { get; set; }
    public int? Threat { get; set; }
    public int? AIDel { get; set; }
    public int? AIDelN { get; set; }
    public int? AIDelH { get; set; }
    public int? AIDist { get; set; }
    public int? AIDistN { get; set; }
    public int? AIDistH { get; set; }
    public int? AIP1 { get; set; }
    public int? AIP1N { get; set; }
    public int? AIP1H { get; set; }
    public int? AIP2 { get; set; }
    public int? AIP2N { get; set; }
    public int? AIP2H { get; set; }
    public int? AIP3 { get; set; }
    public int? AIP3N { get; set; }
    public int? AIP3H { get; set; }
    public int? AIP4 { get; set; }
    public int? AIP4N { get; set; }
    public int? AIP4H { get; set; }
    public int? AIP5 { get; set; }
    public int? AIP5N { get; set; }
    public int? AIP5H { get; set; }
    public int? AIP6 { get; set; }
    public int? AIP6N { get; set; }
    public int? AIP6H { get; set; }
    public int? AIP7 { get; set; }
    public int? AIP7N { get; set; }
    public int? AIP7H { get; set; }
    public int? AIP8 { get; set; }
    public int? AIP8N { get; set; }
    public int? AIP8H { get; set; }
    public string? MissA1 { get; set; }
    public string? MissA2 { get; set; }
    public string? MissS1 { get; set; }
    public string? MissS2 { get; set; }
    public string? MissS3 { get; set; }
    public string? MissS4 { get; set; }
    public string? MissC { get; set; }
    public string? MissSQ { get; set; }
    public int? Align { get; set; }
    public bool? IsSpawn { get; set; }
    public bool? IsMelee { get; set; }
    public bool? Npc { get; set; }
    public bool? Interact { get; set; }
    public bool? Inventory { get; set; }
    public bool? InTown { get; set; }
    public bool? LUndead { get; set; }
    public bool? HUndead { get; set; }
    public bool? Demon { get; set; }
    public bool? Flying { get; set; }
    public bool? OpenDoors { get; set; }
    public bool? Boss { get; set; }
    public bool? PrimeEvil { get; set; }
    public bool? Killable { get; set; }
    public bool? SwitchAI { get; set; }
    public bool? NoAura { get; set; }
    public bool? NoMultiShot { get; set; }
    public bool? NoPreventMonsterHeal { get; set; }
    public bool? NeverCount { get; set; }
    public bool? PetIgnore { get; set; }
    public bool? DeathDmg { get; set; }
    public bool? GenericSpawn { get; set; }
    public bool? Zoo { get; set; }
    public bool? CannotDesecrate { get; set; }
    public bool? CannotHerald { get; set; }
    public string? RightArmItemType { get; set; }
    public string? LeftArmItemType { get; set; }
    public bool? CanNotUseTwoHandedItems { get; set; }
    public int? SendSkills { get; set; }
    public string? Skill1 { get; set; }
    public string? Sk1Mode { get; set; }
    public int? Sk1Lvl { get; set; }
    public string? Skill2 { get; set; }
    public string? Sk2Mode { get; set; }
    public int? Sk2Lvl { get; set; }
    public string? Skill3 { get; set; }
    public string? Sk3Mode { get; set; }
    public int? Sk3Lvl { get; set; }
    public string? Skill4 { get; set; }
    public string? Sk4Mode { get; set; }
    public int? Sk4Lvl { get; set; }
    public string? Skill5 { get; set; }
    public string? Sk5Mode { get; set; }
    public int? Sk5Lvl { get; set; }
    public string? Skill6 { get; set; }
    public string? Sk6Mode { get; set; }
    public int? Sk6Lvl { get; set; }
    public string? Skill7 { get; set; }
    public string? Sk7Mode { get; set; }
    public int? Sk7Lvl { get; set; }
    public string? Skill8 { get; set; }
    public string? Sk8Mode { get; set; }
    public int? Sk8Lvl { get; set; }
    public int? Drain { get; set; }
    public int? DrainN { get; set; }
    public int? DrainH { get; set; }
    public int? ColdEffect { get; set; }
    public int? ColdEffectN { get; set; }
    public int? ColdEffectH { get; set; }
    public int? ResDm { get; set; }
    public int? ResMa { get; set; }
    public int? ResFi { get; set; }
    public int? ResLi { get; set; }
    public int? ResCo { get; set; }
    public int? ResPo { get; set; }
    public int? ResDmN { get; set; }
    public int? ResMaN { get; set; }
    public int? ResFiN { get; set; }
    public int? ResLiN { get; set; }
    public int? ResCoN { get; set; }
    public int? ResPoN { get; set; }
    public int? ResDmH { get; set; }
    public int? ResMaH { get; set; }
    public int? ResFiH { get; set; }
    public int? ResLiH { get; set; }
    public int? ResCoH { get; set; }
    public int? ResPoH { get; set; }
    public int? DamageRegen { get; set; }
    public string? SkillDamage { get; set; }
    public bool? NoRatio { get; set; }
    public int? ShieldBlockOverride { get; set; }
    public int? ToBlock { get; set; }
    public int? ToBlockN { get; set; }
    public int? ToBlockH { get; set; }
    public int? Crit { get; set; }
    public int? MinHP { get; set; }
    public int? MaxHP { get; set; }
    public int? AC { get; set; }
    public int? Exp { get; set; }
    public int? A1MinD { get; set; }
    public int? A1MaxD { get; set; }
    public int? A1TH { get; set; }
    public int? A2MinD { get; set; }
    public int? A2MaxD { get; set; }
    public int? A2TH { get; set; }
    public int? S1MinD { get; set; }
    public int? S1MaxD { get; set; }
    public int? S1TH { get; set; }
    public int? MinHPN { get; set; }
    public int? MaxHPN { get; set; }
    public int? ACN { get; set; }
    public int? ExpN { get; set; }
    public int? A1MinDN { get; set; }
    public int? A1MaxDN { get; set; }
    public int? A1THN { get; set; }
    public int? A2MinDN { get; set; }
    public int? A2MaxDN { get; set; }
    public int? A2THN { get; set; }
    public int? S1MinDN { get; set; }
    public int? S1MaxDN { get; set; }
    public int? S1THN { get; set; }
    public int? MinHPH { get; set; }
    public int? MaxHPH { get; set; }
    public int? ACH { get; set; }
    public int? ExpH { get; set; }
    public int? A1MinDH { get; set; }
    public int? A1MaxDH { get; set; }
    public int? A1THH { get; set; }
    public int? A2MinDH { get; set; }
    public int? A2MaxDH { get; set; }
    public int? A2THH { get; set; }
    public int? S1MinDH { get; set; }
    public int? S1MaxDH { get; set; }
    public int? S1THH { get; set; }
    public string? El1Mode { get; set; }
    public string? El1Type { get; set; }
    public int? El1Pct { get; set; }
    public int? El1MinD { get; set; }
    public int? El1MaxD { get; set; }
    public int? El1Dur { get; set; }
    public int? El1PctN { get; set; }
    public int? El1MinDN { get; set; }
    public int? El1MaxDN { get; set; }
    public int? El1DurN { get; set; }
    public int? El1PctH { get; set; }
    public int? El1MinDH { get; set; }
    public int? El1MaxDH { get; set; }
    public int? El1DurH { get; set; }
    public string? El2Mode { get; set; }
    public string? El2Type { get; set; }
    public int? El2Pct { get; set; }
    public int? El2MinD { get; set; }
    public int? El2MaxD { get; set; }
    public int? El2Dur { get; set; }
    public int? El2PctN { get; set; }
    public int? El2MinDN { get; set; }
    public int? El2MaxDN { get; set; }
    public int? El2DurN { get; set; }
    public int? El2PctH { get; set; }
    public int? El2MinDH { get; set; }
    public int? El2MaxDH { get; set; }
    public int? El2DurH { get; set; }
    public string? El3Mode { get; set; }
    public string? El3Type { get; set; }
    public int? El3Pct { get; set; }
    public int? El3MinD { get; set; }
    public int? El3MaxD { get; set; }
    public int? El3Dur { get; set; }
    public int? El3PctN { get; set; }
    public int? El3MinDN { get; set; }
    public int? El3MaxDN { get; set; }
    public int? El3DurN { get; set; }
    public int? El3PctH { get; set; }
    public int? El3MinDH { get; set; }
    public int? El3MaxDH { get; set; }
    public int? El3DurH { get; set; }
    public string? TreasureClass { get; set; }
    public string? TreasureClassChamp { get; set; }
    public string? TreasureClassUnique { get; set; }
    public string? TreasureClassQuest { get; set; }
    public string? TreasureClassDesecrated { get; set; }
    public string? TreasureClassDesecratedChamp { get; set; }
    public string? TreasureClassDesecratedUnique { get; set; }
    public string? TreasureClassHerald { get; set; }
    public string? TreasureClassN { get; set; }
    public string? TreasureClassChampN { get; set; }
    public string? TreasureClassUniqueN { get; set; }
    public string? TreasureClassQuestN { get; set; }
    public string? TreasureClassDesecratedN { get; set; }
    public string? TreasureClassDesecratedChampN { get; set; }
    public string? TreasureClassDesecratedUniqueN { get; set; }
    public string? TreasureClassHeraldN { get; set; }
    public string? TreasureClassH { get; set; }
    public string? TreasureClassChampH { get; set; }
    public string? TreasureClassUniqueH { get; set; }
    public string? TreasureClassQuestH { get; set; }
    public string? TreasureClassDesecratedH { get; set; }
    public string? TreasureClassDesecratedChampH { get; set; }
    public string? TreasureClassDesecratedUniqueH { get; set; }
    public string? TreasureClassHeraldH { get; set; }
    public int? TCQuestId { get; set; }
    public int? TCQuestCP { get; set; }
    public int? SplEndDeath { get; set; }
    public int? SplGetModeChart { get; set; }
    public int? SplEndGeneric { get; set; }
    public int? SplClientEnd { get; set; }
    public int? Eol { get; set; }
}
