using System.Collections.Generic;
using D2RReimaginedTools.Models;

namespace D2RReimaginedTools.TextFileParsers;

public class MissilesParser : HeaderMappedTextFileParser<Missiles, MissilesParser>
{
    private static readonly IReadOnlyDictionary<string, string[]> Aliases = new Dictionary<string, string[]>
    {
        [nameof(Missiles.MissileName)] = ["Missile"],
        [nameof(Missiles.MissileId)] = ["*ID"],
        [nameof(Missiles.ClientDoFunction)] = ["pCltDoFunc"],
        [nameof(Missiles.ClientHitFunction)] = ["pCltHitFunc"],
        [nameof(Missiles.ServerDoFunction)] = ["pSrvDoFunc"],
        [nameof(Missiles.ServerHitFunction)] = ["pSrvHitFunc"],
        [nameof(Missiles.ServerDamageFunction)] = ["pSrvDmgFunc"],
        [nameof(Missiles.ServerCalculation1)] = ["SrvCalc1"],
        [nameof(Missiles.ServerCalculation1Description)] = ["*srv calc 1 desc"],
        [nameof(Missiles.Param1Description)] = ["*param1 desc"],
        [nameof(Missiles.Param2Description)] = ["*param2 desc"],
        [nameof(Missiles.Param3Description)] = ["*param3 desc"],
        [nameof(Missiles.Param4Description)] = ["*param4 desc"],
        [nameof(Missiles.Param5Description)] = ["*param5 desc"],
        [nameof(Missiles.ClientCalculation1)] = ["CltCalc1"],
        [nameof(Missiles.ClientCalculation1Description)] = ["*client calc 1 desc"],
        [nameof(Missiles.ClientParam1)] = ["CltParam1"],
        [nameof(Missiles.ClientParam1Description)] = ["*client param1 desc"],
        [nameof(Missiles.ClientParam2)] = ["CltParam2"],
        [nameof(Missiles.ClientParam2Description)] = ["*client param2 desc"],
        [nameof(Missiles.ClientParam3)] = ["CltParam3"],
        [nameof(Missiles.ClientParam3Description)] = ["*client param3 desc"],
        [nameof(Missiles.ClientParam4)] = ["CltParam4"],
        [nameof(Missiles.ClientParam4Description)] = ["*client param4 desc"],
        [nameof(Missiles.ClientParam5)] = ["CltParam5"],
        [nameof(Missiles.ClientParam5Description)] = ["*client param5 desc"],
        [nameof(Missiles.ServerHitCalculation1)] = ["SHitCalc1"],
        [nameof(Missiles.ServerHitCalculation1Description)] = ["*server hit calc 1 desc"],
        [nameof(Missiles.ServerHitParam1)] = ["sHitPar1"],
        [nameof(Missiles.ServerHitParam1Description)] = ["*server hit param1 desc"],
        [nameof(Missiles.ServerHitParam2)] = ["sHitPar2"],
        [nameof(Missiles.ServerHitParam2Description)] = ["*server hit param2 desc"],
        [nameof(Missiles.ServerHitParam3)] = ["sHitPar3"],
        [nameof(Missiles.ServerHitParam3Description)] = ["*server hit param3 desc"],
        [nameof(Missiles.ClientHitCalculation1)] = ["CHitCalc1"],
        [nameof(Missiles.ClientHitCalculation1Description)] = ["*client hit calc1 desc"],
        [nameof(Missiles.ClientHitParam1)] = ["cHitPar1"],
        [nameof(Missiles.ClientHitParam1Description)] = ["*client hit param1 desc"],
        [nameof(Missiles.ClientHitParam2)] = ["cHitPar2"],
        [nameof(Missiles.ClientHitParam2Description)] = ["*client hit param2 desc"],
        [nameof(Missiles.ClientHitParam3)] = ["cHitPar3"],
        [nameof(Missiles.ClientHitParam3Description)] = ["*client hit param3 desc"],
        [nameof(Missiles.DamageCalculation1)] = ["DmgCalc1"],
        [nameof(Missiles.DamageCalculation1Description)] = ["*damage calc 1"],
        [nameof(Missiles.DamageParam1)] = ["dParam1"],
        [nameof(Missiles.DamageParam1Description)] = ["*damage param1 desc"],
        [nameof(Missiles.DamageParam2)] = ["dParam2"],
        [nameof(Missiles.DamageParam2Description)] = ["*damage param2 desc"],
        [nameof(Missiles.Velocity)] = ["Vel"],
        [nameof(Missiles.MaxVelocity)] = ["MaxVel"],
        [nameof(Missiles.VelocityLevel)] = ["VelLev"],
        [nameof(Missiles.LevelRange)] = ["Radius"],
        [nameof(Missiles.LoopAnimation)] = ["LoopAnim"],
        [nameof(Missiles.AnimationRate)] = ["animrate"],
        [nameof(Missiles.AnimationLength)] = ["AnimLen"],
        [nameof(Missiles.RandomStart)] = ["RandStart"],
        [nameof(Missiles.ClientCollision)] = ["ClientCol"],
        [nameof(Missiles.SourceTown)] = ["SrcTown"],
        [nameof(Missiles.ClientSourceTown)] = ["CltSrcTown"],
        [nameof(Missiles.SourceDamage)] = ["SrcDamage"],
        [nameof(Missiles.Half2HSource)] = ["Half2HSrc"],
        [nameof(Missiles.SourceMissileDamage)] = ["SrcMissDmg"],
        [nameof(Missiles.MinLevelDamage1)] = ["MinLevDam1"],
        [nameof(Missiles.MinLevelDamage2)] = ["MinLevDam2"],
        [nameof(Missiles.MinLevelDamage3)] = ["MinLevDam3"],
        [nameof(Missiles.MinLevelDamage4)] = ["MinLevDam4"],
        [nameof(Missiles.MinLevelDamage5)] = ["MinLevDam5"],
        [nameof(Missiles.MaxLevelDamage1)] = ["MaxLevDam1"],
        [nameof(Missiles.MaxLevelDamage2)] = ["MaxLevDam2"],
        [nameof(Missiles.MaxLevelDamage3)] = ["MaxLevDam3"],
        [nameof(Missiles.MaxLevelDamage4)] = ["MaxLevDam4"],
        [nameof(Missiles.MaxLevelDamage5)] = ["MaxLevDam5"],
        [nameof(Missiles.DamageSymPerCalculation)] = ["DmgSymPerCalc"],
        [nameof(Missiles.ElementalType)] = ["EType"],
        [nameof(Missiles.ElementalMin)] = ["EMin"],
        [nameof(Missiles.MinElementalLevel1)] = ["MinELev1"],
        [nameof(Missiles.MinElementalLevel2)] = ["MinELev2"],
        [nameof(Missiles.MinElementalLevel3)] = ["MinELev3"],
        [nameof(Missiles.MinElementalLevel4)] = ["MinELev4"],
        [nameof(Missiles.MinElementalLevel5)] = ["MinELev5"],
        [nameof(Missiles.ElementalMax)] = ["EMax"],
        [nameof(Missiles.MaxElementalLevel1)] = ["MaxELev1"],
        [nameof(Missiles.MaxElementalLevel2)] = ["MaxELev2"],
        [nameof(Missiles.MaxElementalLevel3)] = ["MaxELev3"],
        [nameof(Missiles.MaxElementalLevel4)] = ["MaxELev4"],
        [nameof(Missiles.MaxElementalLevel5)] = ["MaxELev5"],
        [nameof(Missiles.ElementalDamageSymPerCalculation)] = ["EDmgSymPerCalc"],
        [nameof(Missiles.ElementalLength)] = ["ELen"],
        [nameof(Missiles.ElementalLevelLength1)] = ["ELevLen1"],
        [nameof(Missiles.ElementalLevelLength2)] = ["ELevLen2"],
        [nameof(Missiles.ElementalLevelLength3)] = ["ELevLen3"],
        [nameof(Missiles.NumberOfDirections)] = ["NumDirections"],
        [nameof(Missiles.ProgressSound)] = ["ProgSound"],
        [nameof(Missiles.ProgressOverlay)] = ["ProgOverlay"],
        [nameof(Missiles.ClientSubMissile1)] = ["CltSubMissile1"],
        [nameof(Missiles.ClientSubMissile2)] = ["CltSubMissile2"],
        [nameof(Missiles.ClientSubMissile3)] = ["CltSubMissile3"],
        [nameof(Missiles.ClientHitSubMissile1)] = ["CltHitSubMissile1"],
        [nameof(Missiles.ClientHitSubMissile2)] = ["CltHitSubMissile2"],
        [nameof(Missiles.ClientHitSubMissile3)] = ["CltHitSubMissile3"],
        [nameof(Missiles.Acceleration)] = ["Accel"],
        [nameof(Missiles.AnimationSpeed)] = ["AnimSpeed"],
        [nameof(Missiles.ClientHitSubMissile4)] = ["CltHitSubMissile4"]
    };

    protected override IReadOnlyDictionary<string, string[]> PropertyColumnAliases => Aliases;
}
