using D2RReimaginedTools.Extensions;
using D2RReimaginedTools.Models;

namespace D2RReimaginedTools.TextFileParsers;
public static class MissilesParser
{
    public static async Task<IList<Missiles>> GetEntries(string path)
    {
        var lines = (await TextFileParserFileUtility.ReadAllLinesAsync(typeof(MissilesParser), path)).Skip(1);
        return lines.Select(columns => columns.Split('\t'))
                    .Select(columns => new Missiles
                    {
                        MissileName = columns[0],
                        MissileId = columns[1].ToInt(),
                        ClientDoFunction = columns[2].ToNullableInt(),
                        ClientHitFunction = columns[3].ToNullableInt(),
                        ServerDoFunction = columns[4].ToNullableInt(),
                        ServerHitFunction = columns[5].ToNullableInt(),
                        ServerDamageFunction = columns[6].ToNullableInt(),
                        ServerCalculation1 = columns[7],
                        ServerCalculation1Description = columns[8],
                        Param1 = columns[9].ToNullableInt(),
                        Param1Description = columns[10],
                        Param2 = columns[11].ToNullableInt(),
                        Param2Description = columns[12],
                        Param3 = columns[13].ToNullableInt(),
                        Param3Description = columns[14],
                        Param4 = columns[15].ToNullableInt(),
                        Param4Description = columns[16],
                        Param5 = columns[17].ToNullableInt(),
                        Param5Description = columns[18],
                        ClientCalculation1 = columns[19],
                        ClientCalculation1Description = columns[20],
                        ClientParam1 = columns[21].ToNullableInt(),
                        ClientParam1Description = columns[22],
                        ClientParam2 = columns[23].ToNullableInt(),
                        ClientParam2Description = columns[24],
                        ClientParam3 = columns[25].ToNullableInt(),
                        ClientParam3Description = columns[26],
                        ClientParam4 = columns[27].ToNullableInt(),
                        ClientParam4Description = columns[28],
                        ClientParam5 = columns[29].ToNullableInt(),
                        ClientParam5Description = columns[30],
                        ServerHitCalculation1 = columns[31],
                        ServerHitCalculation1Description = columns[32],
                        ServerHitParam1 = columns[33].ToNullableInt(),
                        ServerHitParam1Description = columns[34],
                        ServerHitParam2 = columns[35].ToNullableInt(),
                        ServerHitParam2Description = columns[36],
                        ServerHitParam3 = columns[37].ToNullableInt(),
                        ServerHitParam3Description = columns[38],
                        ClientHitCalculation1 = columns[39],
                        ClientHitCalculation1Description = columns[40],
                        ClientHitParam1 = columns[41].ToNullableInt(),
                        ClientHitParam1Description = columns[42],
                        ClientHitParam2 = columns[43].ToNullableInt(),
                        ClientHitParam2Description = columns[44],
                        ClientHitParam3 = columns[45].ToNullableInt(),
                        ClientHitParam3Description = columns[46],
                        DamageCalculation1 = columns[47],
                        DamageCalculation1Description = columns[48],
                        DamageParam1 = columns[49],
                        DamageParam1Description = columns[50],
                        DamageParam2 = columns[51],
                        DamageParam2Description = columns[52],
                        Velocity = columns[53].ToNullableInt(),
                        MaxVelocity = columns[54].ToNullableInt(),
                        VelocityLevel = columns[55].ToNullableInt(),
                        Acceleration = columns[56].ToNullableInt(),
                        Range = columns[57].ToNullableInt(),
                        LevelRange = columns[58].ToNullableInt(),
                        Light = columns[59].ToNullableInt(),
                        Flicker = columns[60].ToNullableInt(),
                        Red = columns[61].ToNullableInt(),
                        Green = columns[62].ToNullableInt(),
                        Blue = columns[63].ToNullableInt(),
                        InitSteps = columns[64].ToNullableInt(),
                        Activate = columns[65].ToNullableInt(),
                        LoopAnimation = columns[66].ToNullableInt(),
                        CelFile = columns[67],
                        AnimationRate = columns[68].ToNullableInt(),
                        AnimationLength = columns[69].ToNullableInt(),
                        AnimationSpeed = columns[70].ToNullableInt(),
                        RandomStart = columns[71].ToNullableInt(),
                        SubLoop = columns[72].ToNullableInt(),
                        SubStart = columns[73].ToNullableInt(),
                        SubStop = columns[74].ToNullableInt(),
                        CollideType = columns[75].ToNullableInt(),
                        CollideKill = columns[76].ToNullableInt(),
                        CollideFriend = columns[77].ToNullableInt(),
                        LastCollide = columns[78].ToNullableInt(),
                        Collision = columns[79].ToNullableInt(),
                        ClientCollision = columns[80].ToNullableInt(),
                        CollisionOverlap = columns[81].ToNullableInt(),
                        ClientSend = columns[82].ToNullableInt(),
                        NextHit = columns[83].ToNullableInt(),
                        NextDelay = columns[84].ToNullableInt(),
                        XOffset = columns[85].ToNullableInt(),
                        YOffset = columns[86].ToNullableInt(),
                        ZOffset = columns[87].ToNullableInt(),
                        Size = columns[88].ToNullableInt(),
                        SourceTown = columns[89].ToNullableInt(),
                        ClientSourceTown = columns[90].ToNullableInt(),
                        CanDestroy = columns[91].ToNullableInt(),
                        ToHit = columns[92].ToNullableInt(),
                        AlwaysExplode = columns[93].ToNullableInt(),
                        Explosion = columns[94],
                        Town = columns[95].ToNullableInt(),
                        NoUniqueMod = columns[96].ToNullableInt(),
                        NoMultiShot = columns[97].ToNullableInt(),
                        Holy = columns[98].ToNullableInt(),
                        CanSlow = columns[99].ToNullableInt(),
                        ReturnFire = columns[100].ToNullableInt(),
                        GetHit = columns[101].ToNullableInt(),
                        SoftHit = columns[102].ToNullableInt(),
                        KnockBack = columns[103].ToNullableInt(),
                        Trans = columns[104],
                        Pierce = columns[105].ToNullableInt(),
                        MissileSkill = columns[106].ToNullableInt(),
                        Skill = columns[107],
                        ResultFlags = columns[108].ToNullableInt(),
                        HitFlags = columns[109].ToNullableInt(),
                        HitShift = columns[110].ToNullableInt(),
                        ApplyMastery = columns[111].ToNullableInt(),
                        SourceDamage = columns[112].ToNullableInt(),
                        Half2HSource = columns[113].ToNullableInt(),
                        SourceMissileDamage = columns[114].ToNullableInt(),
                        MinDamage = columns[115].ToNullableInt(),
                        MinLevelDamage1 = columns[116].ToNullableInt(),
                        MinLevelDamage2 = columns[117].ToNullableInt(),
                        MinLevelDamage3 = columns[118].ToNullableInt(),
                        MinLevelDamage4 = columns[119].ToNullableInt(),
                        MinLevelDamage5 = columns[120].ToNullableInt(),
                        MaxDamage = columns[121].ToNullableInt(),
                        MaxLevelDamage1 = columns[122].ToNullableInt(),
                        MaxLevelDamage2 = columns[123].ToNullableInt(),
                        MaxLevelDamage3 = columns[124].ToNullableInt(),
                        MaxLevelDamage4 = columns[125].ToNullableInt(),
                        MaxLevelDamage5 = columns[126].ToNullableInt(),
                        DamageSymPerCalculation = columns[127],
                        ElementalType = columns[128],
                        ElementalMin = columns[129].ToNullableInt(),
                        MinElementalLevel1 = columns[130].ToNullableInt(),
                        MinElementalLevel2 = columns[131].ToNullableInt(),
                        MinElementalLevel3 = columns[132].ToNullableInt(),
                        MinElementalLevel4 = columns[133].ToNullableInt(),
                        MinElementalLevel5 = columns[134].ToNullableInt(),
                        ElementalMax = columns[135].ToNullableInt(),
                        MaxElementalLevel1 = columns[136].ToNullableInt(),
                        MaxElementalLevel2 = columns[137].ToNullableInt(),
                        MaxElementalLevel3 = columns[138].ToNullableInt(),
                        MaxElementalLevel4 = columns[139].ToNullableInt(),
                        MaxElementalLevel5 = columns[140].ToNullableInt(),
                        ElementalDamageSymPerCalculation = columns[141],
                        ElementalLength = columns[142],
                        ElementalLevelLength1 = columns[143].ToNullableInt(),
                        ElementalLevelLength2 = columns[144].ToNullableInt(),
                        ElementalLevelLength3 = columns[145].ToNullableInt(),
                        HitClass = columns[146],
                        NumberOfDirections = columns[147].ToNullableInt(),
                        LocalBlood = columns[148].ToNullableInt(),
                        DamageRate = columns[149].ToNullableInt(),
                        TravelSound = columns[150],
                        HitSound = columns[151],
                        OnDiedSound = columns[152],
                        ProgressSound = columns[153],
                        ProgressOverlay = columns[154],
                        ExplosionMissile = columns[155],
                        SubMissile1 = columns[156],
                        SubMissile2 = columns[157],
                        SubMissile3 = columns[158],
                        HitSubMissile1 = columns[159],
                        HitSubMissile2 = columns[160],
                        HitSubMissile3 = columns[161],
                        HitSubMissile4 = columns[162],
                        ClientSubMissile1 = columns[163],
                        ClientSubMissile2 = columns[164],
                        ClientSubMissile3 = columns[165],
                        ClientHitSubMissile1 = columns[166],
                        ClientHitSubMissile2 = columns[167],
                        ClientHitSubMissile3 = columns[168],
                        ClientHitSubMissile4 = columns[169],
                        MissileWeaponVFX = columns[170],
                        Eol = columns[171].ToNullableInt(),

                    }).ToList();
    }


    public static Task<FileInfo> SaveEntries(IList<Missiles> entries, string? sourcePath = null, string? outputDirectory = null, CancellationToken cancellationToken = default)
    {
        return TextFileParserFileUtility.SaveEntriesAsync<Missiles>(typeof(MissilesParser), entries, sourcePath, outputDirectory, cancellationToken);
    }
}

