using D2RReimaginedTools.Extensions;
using D2RReimaginedTools.Models;

namespace D2RReimaginedTools.FileParsers;

public class MonStats2Parser
{
    public static async Task<IList<MonStats2>> GetEntries(string path)
    {
        var lines = (await File.ReadAllLinesAsync(path)).Skip(1); // Skip header line

        return lines.Select(line => line.Split('\t'))
            .Select(columns => new MonStats2
            {
                Id = columns[0],
                HcIdx = columns[1].ToInt(),
                Height = columns[2].ToInt(),
                OverlayHeight = columns[3].ToInt(),
                PixHeight = columns[4].ToInt(),
                SizeX = columns[5].ToInt(),
                SizeY = columns[6].ToInt(),
                SpawnCol = columns[7].ToInt(),
                MeleeRng = columns[8],
                BaseW = columns[9],
                HitClass = columns[10].ToInt(),
                HDv = columns[11],
                TRv = columns[12],
                LGv = columns[13],
                Rav = columns[14],
                Lav = columns[15],
                RHv = columns[16],
                LHv = columns[17],
                SHv = columns[18],
                S1v = columns[19],
                S2v = columns[20],
                S3v = columns[21],
                S4v = columns[22],
                S5v = columns[23],
                S6v = columns[24],
                S7v = columns[25],
                S8v = columns[26],
                HD = columns[27],
                TR = columns[28],
                LG = columns[29],
                RA = columns[30],
                LA = columns[31],
                RH = columns[32],
                LH = columns[33],
                SH = columns[34],
                S1 = columns[35],
                S2 = columns[36],
                S3 = columns[37],
                S4 = columns[38],
                S5 = columns[39],
                S6 = columns[40],
                S7 = columns[41],
                S8 = columns[42],
                TotalPieces = columns[43].ToInt(),
                MDT = columns[44].ToInt(),
                MNU = columns[45].ToInt(),
                MWL = columns[46].ToInt(),
                MGH = columns[47].ToInt(),
                MA1 = columns[48].ToInt(),
                MA2 = columns[49].ToInt(),
                MBL = columns[50].ToInt(),
                MSC = columns[51].ToInt(),
                MS1 = columns[52].ToInt(),
                MS2 = columns[53].ToInt(),
                MS3 = columns[54].ToInt(),
                MS4 = columns[55].ToInt(),
                MDD = columns[56].ToInt(),
                MKB = columns[57].ToInt(),
                MSQ = columns[58].ToInt(),
                MRN = columns[59].ToInt(),
                DDT = columns[60].ToInt(),
                DNU = columns[61].ToInt(),
                DWL = columns[62].ToInt(),
                DGH = columns[63].ToInt(),
                DA1 = columns[64].ToInt(),
                DA2 = columns[65].ToInt(),
                DBL = columns[66].ToInt(),
                DSC = columns[67].ToInt(),
                DS1 = columns[68].ToInt(),
                DS2 = columns[69].ToInt(),
                DS3 = columns[70].ToInt(),
                DS4 = columns[71].ToInt(),
                DDD = columns[72].ToInt(),
                DKB = columns[73].ToInt(),
                DSQ = columns[74].ToInt(),
                DRN = columns[75].ToInt(),
                A1mv = columns[76].ToInt(),
                A2mv = columns[77].ToInt(),
                SCmv = columns[78].ToInt(),
                S1mv = columns[79].ToInt(),
                S2mv = columns[80].ToInt(),
                S3mv = columns[81].ToInt(),
                S4mv = columns[82].ToInt(),
                NoGfxHitTest = columns[83].ToInt(),
                HtTop = columns[84].ToInt(),
                HtLeft = columns[85].ToInt(),
                HtWidth = columns[86].ToInt(),
                HtHeight = columns[87].ToInt(),
                Restore = columns[88].ToInt(),
                AutomapCel = columns[89],
                NoMap = columns[90].ToInt(),
                NoOvly = columns[91].ToInt(),
                IsSel = columns[92].ToInt(),
                AlSel = columns[93].ToInt(),
                NoSel = columns[94].ToInt(),
                ShiftSel = columns[95].ToInt(),
                CorpseSel = columns[96].ToInt(),
                IsAtt = columns[97].ToInt(),
                Revive = columns[98].ToInt(),
                LimitCorpses = columns[99].ToInt(),
                Critter = columns[100].ToInt(),
                Small = columns[101].ToInt(),
                Large = columns[102].ToInt(),
                Soft = columns[103].ToInt(),
                Inert = columns[104].ToInt(),
                ObjCol = columns[105].ToInt(),
                DeadCol = columns[106].ToInt(),
                UnflatDead = columns[107].ToInt(),
                Shadow = columns[108],
                NoUniqueShift = columns[109].ToInt(),
                CompositeDeath = columns[110],
                LocalBlood = columns[111],
                Bleed = columns[112].ToBool(),
                Light = columns[113],
                LightR = columns[114].ToInt(),
                LightG = columns[115].ToInt(),
                LightB = columns[116].ToInt(),
                Utrans = columns[117],
                UtransN = columns[118],
                UtransH = columns[119],
                InfernoLen = columns[120].ToInt(),
                InfernoAnim = columns[121],
                InfernoRollback = columns[122].ToInt(),
                ResurrectMode = columns[123],
                ResurrectSkill = columns[124],
                SpawnUniqueMod = columns[125],
            }).ToList();
    }
}