using System.Collections.Generic;
using D2RReimaginedTools.Models;

namespace D2RReimaginedTools.TextFileParsers;

public class SkillDescParser : HeaderMappedTextFileParser<SkillDesc, SkillDescParser>
{
    private static readonly IReadOnlyDictionary<string, string[]> Aliases = new Dictionary<string, string[]>
    {
        [nameof(SkillDesc.SkillName)] = ["skilldesc"],
        [nameof(SkillDesc.NameString)] = ["str name"],
        [nameof(SkillDesc.ShortString)] = ["str short"],
        [nameof(SkillDesc.LongString)] = ["str long"],
        [nameof(SkillDesc.AlternateString)] = ["str alt"],
        [nameof(SkillDesc.DescriptionDamage)] = ["descdam"],
        [nameof(SkillDesc.DamageCalculation1)] = ["ddam calc1"],
        [nameof(SkillDesc.DamageCalculation2)] = ["ddam calc2"],
        [nameof(SkillDesc.Param1Element)] = ["p1dmelem"],
        [nameof(SkillDesc.Param1Min)] = ["p1dmmin"],
        [nameof(SkillDesc.Param1Max)] = ["p1dmmax"],
        [nameof(SkillDesc.Param2Element)] = ["p2dmelem"],
        [nameof(SkillDesc.Param2Min)] = ["p2dmmin"],
        [nameof(SkillDesc.Param2Max)] = ["p2dmmax"],
        [nameof(SkillDesc.Param3Element)] = ["p3dmelem"],
        [nameof(SkillDesc.Param3Min)] = ["p3dmmin"],
        [nameof(SkillDesc.Param3Max)] = ["p3dmmax"],
        [nameof(SkillDesc.DescriptionAttack)] = ["descatt"],
        [nameof(SkillDesc.DescriptionMissile1)] = ["descmissile1"],
        [nameof(SkillDesc.DescriptionMissile2)] = ["descmissile2"],
        [nameof(SkillDesc.DescriptionMissile3)] = ["descmissile3"],
        [nameof(SkillDesc.DescriptionLine1)] = ["descline1"],
        [nameof(SkillDesc.DescriptionTextA1)] = ["desctexta1"],
        [nameof(SkillDesc.DescriptionTextB1)] = ["desctextb1"],
        [nameof(SkillDesc.DescriptionCalculationA1)] = ["desccalca1"],
        [nameof(SkillDesc.DescriptionCalculationB1)] = ["desccalcb1"],
        [nameof(SkillDesc.DescriptionLine2)] = ["descline2"],
        [nameof(SkillDesc.DescriptionTextA2)] = ["desctexta2"],
        [nameof(SkillDesc.DescriptionTextB2)] = ["desctextb2"],
        [nameof(SkillDesc.DescriptionCalculationA2)] = ["desccalca2"],
        [nameof(SkillDesc.DescriptionCalculationB2)] = ["desccalcb2"],
        [nameof(SkillDesc.DescriptionLine3)] = ["descline3"],
        [nameof(SkillDesc.DescriptionTextA3)] = ["desctexta3"],
        [nameof(SkillDesc.DescriptionTextB3)] = ["desctextb3"],
        [nameof(SkillDesc.DescriptionCalculationA3)] = ["desccalca3"],
        [nameof(SkillDesc.DescriptionCalculationB3)] = ["desccalcb3"],
        [nameof(SkillDesc.DescriptionLine4)] = ["descline4"],
        [nameof(SkillDesc.DescriptionTextA4)] = ["desctexta4"],
        [nameof(SkillDesc.DescriptionTextB4)] = ["desctextb4"],
        [nameof(SkillDesc.DescriptionCalculationA4)] = ["desccalca4"],
        [nameof(SkillDesc.DescriptionCalculationB4)] = ["desccalcb4"],
        [nameof(SkillDesc.DescriptionLine5)] = ["descline5"],
        [nameof(SkillDesc.DescriptionTextA5)] = ["desctexta5"],
        [nameof(SkillDesc.DescriptionTextB5)] = ["desctextb5"],
        [nameof(SkillDesc.DescriptionCalculationA5)] = ["desccalca5"],
        [nameof(SkillDesc.DescriptionCalculationB5)] = ["desccalcb5"],
        [nameof(SkillDesc.DescriptionLine6)] = ["descline6"],
        [nameof(SkillDesc.DescriptionTextA6)] = ["desctexta6"],
        [nameof(SkillDesc.DescriptionTextB6)] = ["desctextb6"],
        [nameof(SkillDesc.DescriptionCalculationA6)] = ["desccalca6"],
        [nameof(SkillDesc.DescriptionCalculationB6)] = ["desccalcb6"],
        [nameof(SkillDesc.Dsc2CalculationA1)] = ["dsc2calca1"],
        [nameof(SkillDesc.Dsc2CalculationB1)] = ["dsc2calcb1"],
        [nameof(SkillDesc.Dsc2CalculationA2)] = ["dsc2calca2"],
        [nameof(SkillDesc.Dsc2CalculationB2)] = ["dsc2calcb2"],
        [nameof(SkillDesc.Dsc2CalculationA3)] = ["dsc2calca3"],
        [nameof(SkillDesc.Dsc2CalculationB3)] = ["dsc2calcb3"],
        [nameof(SkillDesc.Dsc2CalculationA4)] = ["dsc2calca4"],
        [nameof(SkillDesc.Dsc2CalculationB4)] = ["dsc2calcb4"],
        [nameof(SkillDesc.Dsc2CalculationA5)] = ["dsc2calca5"],
        [nameof(SkillDesc.Dsc2CalculationB5)] = ["dsc2calcb5"],
        [nameof(SkillDesc.Dsc3CalculationA1)] = ["dsc3calca1"],
        [nameof(SkillDesc.Dsc3CalculationB1)] = ["dsc3calcb1"],
        [nameof(SkillDesc.Dsc3CalculationA2)] = ["dsc3calca2"],
        [nameof(SkillDesc.Dsc3CalculationB2)] = ["dsc3calcb2"],
        [nameof(SkillDesc.Dsc3CalculationA3)] = ["dsc3calca3"],
        [nameof(SkillDesc.Dsc3CalculationB3)] = ["dsc3calcb3"],
        [nameof(SkillDesc.Dsc3CalculationA4)] = ["dsc3calca4"],
        [nameof(SkillDesc.Dsc3CalculationB4)] = ["dsc3calcb4"],
        [nameof(SkillDesc.Dsc3CalculationA5)] = ["dsc3calca5"],
        [nameof(SkillDesc.Dsc3CalculationB5)] = ["dsc3calcb5"],
        [nameof(SkillDesc.Dsc3CalculationA6)] = ["dsc3calca6"],
        [nameof(SkillDesc.Dsc3CalculationB6)] = ["dsc3calcb6"],
        [nameof(SkillDesc.Dsc3CalculationA7)] = ["dsc3calca7"],
        [nameof(SkillDesc.Dsc3CalculationB7)] = ["dsc3calcb7"],
        [nameof(SkillDesc.ItemProcDescriptionLineCount)] = ["item proc descline count"],
        [nameof(SkillDesc.EndOfLine)] = ["*eol"]
    };

    protected override IReadOnlyDictionary<string, string[]> PropertyColumnAliases => Aliases;
}
